# -*- coding: utf-8 -*-
"""Python Beginner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-sQWuveXVStlhTtj4LR3uC8AwR_f7Qk

Problem: You have been given a dataset for marks of 2 subjects, scored by students of classes ClassA and ClassB. You now want to compare the performances of class A and class B by finding out the average performance of the classes. Write a program to find if class A performed better. Print True is Class A is strictly better else return False.
"""

A1=int(input())
A2=int(input())
B1=int(input())
B2=int(input())
A=(A1+A2)/2
B=(B1+B2)/2
if A>B:
    print(True)
else:
    print(False)

"""Problem: Write a program that takes the age of the user as input and tells them if they're old enough to ride a roller coaster. The minimum age to ride the roller coaster in this question is 13."""

a=int(input())
if a>=13:
    print("You can ride the roller coaster!")
else:
    print("You can't ride the roller coaster.")

"""Problem: You are given 3 integer angles(in degrees) A, B and C of a triangle. You have to tell whether the triangle is valid or not. Print 1 if the triangle having given sides is valid, else print 0."""

A=int(input())
B=int(input())
C=int(input())
x=A+B+C
if x==180:
    print('1')
else:
    print('0')

"""Problem: Write a program that takes in a number N as input and does the following:

if N is a multiple of 3, print Fizz
if N is a multiple of 5, print Buzz
if N is a multiple of both 3 and 5, print FizzBuzz
"""

n= int(input())
if n%3==0 and n%5==0:
    print('FizzBuzz')
elif n%3==0:
    print('Fizz')
elif n%5==0:
    print('Buzz')

"""Problem: Given an integer A representing an year, Return 1 if it is a leap year else return 0. A year is leap year if the following conditions are satisfied:
1. Year is multiple of 400.
2. Else the year is multiple of 4 and not multiple of 100.
"""

a=int(input())
if a%400==0 or a%4==0 and a%100!=0:
    print("1")
else:
    print('0')

"""Problem: In this exercise, you need to implement some rules from Pac-Man, the classic 1980s-era arcade-game.

You have to answer whether the Pac-Man loses or not.

Your are given the following integer inputs (0 / 1) one in each line:

1. Does the Pac-Man have a power pellect active?

2. Is the Pac-Man touching a ghost?

The Pac-Man loses if it is touching a ghost and does not have a power pellet active. Print 1 if the Pac-Man loses else 0.
"""

power=int(input())
touch=int(input())
if power==0 and touch==1:
    print('1')
else:
    print('0')

"""Problem: Take an integer A as input. You have to tell whether A is divible by both 5 and 11 or not. Print 1 if A is divisible by both 5 and 11, else print 0."""

a=int(input())
if a%5==0 and a%11==0:
    print('1')
else:
    print('0')

"""Problem: Given a number A. Print all perfect squares less than or equal to A.
Notes - Perfect squares are integers whose square root is an integer.
"""

a=int(input())
i=1
while i<=a:
  if i*i<=a:
    print(i**2,end=" ")
  i+=1

"""Problem: Take a number A as input, print its multiplication table having the first 10 multiples."""

a=int(input())
i=1
while i<=a*2:
    print(a,"*",i,"=",i*a)
    i+=1

"""Problem: Take T (number of test cases) as input.
For each test case, take integer N as input and Print the sum of digits of that number.
"""

t=int(input())
i=1
while i<=t:
  n=int(input())
  sum=0
  while n!=0:
    sum=sum+(n%10)
    n//=10
  print(sum)
  i+=1

"""Problem: Write a program to print all Natural numbers from N to 1 where you have to take N as input from user."""

n=int(input())
for i in range(n,0,-1):
    print(i,end=" ")

"""Problem: Take an integer A as input. You have to print the sum of all odd numbers in the range [1, A]."""

a=int(input())
s=0
for i in range(1,a+1):
    if i%2!=0:
        s=s+i
    else:
        pass
print(s)

"""Problem: Take an integer A as input, determine whether it is palindromic or not.

A palindrome integer is an integer X for which reverse(X) = X where reverse(X) is X with its digits reversed. For e.g., reverse(123) = 321. Note : There will be no zeros at the start of a number.
"""

a=input()
if a==a[::-1]:
    print("Yes")
else:
    print("No")

"""Problem: Write a program that accepts T numbers(N) from the user and find reverse of the given number(N)."""

t=int(input())
for i in range(1,t+1):
    n=int(input())
    m=0
    while n!=0:
      r=n%10
      m=m*10+r
      n=n//10
    print(m)

"""Problem: Write a program to input an integer T and then for each test case input two integers A and B in two different lines and then print T lines containing Least Common Multiple (LCM) of two given 2 numbers A and B.

LCM of two integers is the smallest positive integer divisible by both.
"""

t=int(input())
for i in range(1,t+1):
    a=int(input())
    b=int(input())
    #x=max(a,b)
    for i in range(1,a*b+1):
      if i%a==0 and i%b==0:
        print(i)
        break

"""Problem: Write a program to input an integer T which represents the number of test cases. For each test case input two integers A and B in two different lines. For each pair of A and B print the HCF of the given two numbers."""

t=int(input())
for i in range(0,t):
    a=int(input())
    b=int(input())
    x=min(a,b)
    for i in range(x,0,-1):
        if a%i==0 and b%i==0:
            print(i)
            break

"""Problem: Take an integer N as input, print the Numeric Inverted Half Pyramid pattern for N."""

n=int(input())
i=1
while i<=n:
  for j in range(1,n+1):
    if j==n:
      print(j,end='')
    else:
      print(j,end=" ")
  print()
  n=n-1
i+=1

"""Problem: Two Line Star Pattern"""

n=int(input())
for i in range(1,n+1):
  print("*" + " "*(n-2) + "*")

"""Problem: Take an integer N, print the Full Pyramid pattern for N."""

n=int(input())
for i in range(1,n+1):
    for j in range(n-i):
        print(" ",end="")
    for k in range(i):
        print("* ",end="")
    print()

"""Problem: Given the temperature of a day in Degrees Celsius, convert this given temperature from Celsius to Fahrenheit. Write a program to do so. Round the output up to 2 decimal places"""

def celsius_farhen(x):
    ans = 0
    return round(x*1.8+32,2)
    ans=celsius_farhen(x)

celsius_farhen(99)

"""Problem: Given an integer n, write a program to print the sum of squares of first n natural numbers in integer format. The formula for the sum of squares of first n natural numbers is: n(n+1)(2n+1)/6"""

def sum_squares(n):
    ans = None
    return n*(n+1)*(2*n+1)//6

sum_squares(89)

"""Problem: Write a function to check whether a given number n as an input to the function is a perfect number or not. If the given integer is a perfect number return 1 else return 0.

Note: In number theory, a perfect number is a positive integer that is equal to the sum of its proper positive divisors, that is, the sum of its positive divisors excluding the number itself (also known as its aliquot sum).
"""

def perfect_number(n):

    s=0
    for i in range(1,n):
        if n%i==0:
            s=s+i
    if s==n and n>=0:
        print("1")
    else:
        print("0")

"""Problem: Given three integers, A, B and C. You have to find the number of days it will take to reach zero cases of Corona in a city.

A - Average cases recovered in a day of the corona.
B - Number of new cases of corona daily.
C - Current active cases of the corona.

Return the minimum number of days it will take to reach 0 active cases of Covid.
"""

def solve(self, A, B, C):
    days=0
    while C>0:
        C=C+B
        C=C-A
        days=days+1
    return days

"""Given an integer A, find the rounded value of real number A / 200.

Rounded value of a real number X is the integer which is nearest to X, with halfway cases rounded away from zero.

Some examples:

Rounded value of 2.4 = 2
Rounded value of 2.5 = 3
Rounded value of 2.6 = 3
Rounded value of 0.0 = 0
Rounded value of -2.4 = -2
Rounded value of -2.5 = -3
Rounded value of -2.6 = -3
"""

def solve(self, A):
    ans=0
    n=A/200
    m=int(n)
    if n>0:
        if n>=m+0.5:
            ans=m+1
        else:
            ans=m
    else:
        if n>m-0.5:
            ans=m
        else:
            ans=m-1
    return ans

"""Problem:Given the height (A) and weight (B) of a person as input in centimetres and kilograms.

Find the BMI of that person and the classification of the user based on their BMI.

Print Underweight if BMI < 18.5
Print Normal weight if BMI lies in the range [18.5, 24.9]
Print Overweight if BMI lies in the range (24.9, 29.9]
Print Obese if BMI is greater than 29.9
If x is the weight in kilograms and y is the height in metres.

Then, BMI is calculated as x/(y*y).
"""

def main(a,b):
    a=a/100
    bmi=round(b/(a*a),1)
    if bmi<18.5:
        print('Underweight')
        print(bmi)
    elif bmi<=24.9 and bmi>=18.5:
        print('Normal Weight')
        print(bmi)
    elif bmi<=29.9 and bmi>=24.9:
        print('Overweight')
        print(bmi)
    elif bmi>29.9:
        print('Obese')
        print(bmi)


a=float(input())
b=float(input())

main(a,b)
